definitions = {
'statut': 'regulamin, kodeks',
'dyskryminacja': 'gorsze traktowanie z powodu odmienności',
'dyskryminacyjnego': 'związanego z gorszym traktowaniem z powodu odmienności',
'pochodzenie etniczne': 'naród lub mniejszość narodowa, z której ktoś pochodzi',
'werbalne': 'słowne, ustne',
'pozawerbalne': 'przekazywane czymś innym niż słowami',
'mobbing': 'nękanie, przemoc psychiczna',
'mobbingowi': 'nękaniu, przemoc psychiczna',
'mobbingu': 'nękania, przemocy psychiczna',
'wyelminowanie': 'pozbycie się',
'izolować': 'unikać, trzymać w odosobnieniu',
'zadośćuczynienia': 'odszkodowanie',
'normy prawne': 'obowiązujące zasady prawidłowego postępowania',
'układów zbiorowych': 'umów o warunkach pracy',
'ustawie': 'zasadzie prawnej',
'porozumień zbiorowych': 'umowów o warunkach pracy',
'art.': 'artykuł, część dokumentu prawnego',
'akt': 'dokument',
'stosunek pracy': 'obowiązki pracownika i pracodawcy związane z zatrudnieniem',
'stosunku pracy': 'obowiązki pracownika i pracodawcy związane z zatrudnieniem',
'awansowania': 'dostania lepszej pracy',
'awansowaniu': 'dostaniu lepszej pracy',
'kwalifikacji zawodowych': 'umiejętności przydantych w pracy',
'pozornie': 'nieprawdziwie, ale takie się wydaje',
'dysproporcje': 'nierówności',
'obiektywnie': 'zawsze prawdziwie'
}
